##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.deployment.annotations }}
    annotations:
{{ toYaml .Values.deployment.annotations | indent 8 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Release.Name }}
    spec:
      hostname: {{ .Release.Name }}
      imagePullSecrets:
        - name: {{ .Values.expressapp.pullSecrets }}
      containers:     
      - name: expressapp
        image: {{ .Values.expressapp.image }}
        imagePullPolicy: {{ .Values.expressapp.pullPolicy }}
        env:
        - name: API_URL
          value: "{{ .Values.expressapp.apiUrl }}"
        - name: PORT
          value: "{{ .Values.expressapp.nodePorts.targetPort }}"
        ports:
        - containerPort: {{ .Values.expressapp.nodePorts.targetPort }}
          name: expressapp

