##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Create postgresql values file for the peer nodes
- name: "Create postgresql values file for all peers"
  include_role:
    name: helm_component
  vars:
    type: "postgresql"
    name: "{{ peer.name }}"
    charts_dir: "examples/dscp-app/charts"
    component_name: "{{ peer.name }}-postgresql"
    username: "{{ peer.postgresql.user }}"
    password: "{{ peer.postgresql.password }}"
    first_db_name: "{{ peer.id_service.db_name }}"
    second_db_name: "{{ peer.inteli_api.db_name }}"
    postgres_port: "{{ peer.postgresql.port }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)

# Push the postgresql deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ component_gitops }}"
    GIT_RESET_PATH: "examples/dscp-app/configuration"
    msg: "[ci skip] Pushing deployment files for postgresql"

# Wait for postgresql Pod to run
- name: "Waiting for postgresql pod in {{ component_ns }}"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ component_ns }}"
    component_name: "{{ peer.name }}-postgresql"
    kubernetes: "{{ org.k8s }}"
    label_selectors:
      - app.kubernetes.io/instance = {{ component_name }}
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)
