apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiertwo-api
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscpapp
        namespace: flux-dscpapp
      chart: examples/dscp-app/charts/dscp-api
  releaseName: tiertwo-api
  values:
    fullNameOverride: tiertwo-api
    config:
      port: 80
      externalNodeHost: "tiertwo"
      externalNodePort: 9944
      logLevel: info  
      externalIpfsHost: "tiertwo-ipfs-api" 
      externalIpfsPort: 5001 
      enableLivenessProbe: true
      substrateStatusPollPeriodMs: 10000
      substrateStatusTimeoutMs: 200000
      ipfsStatusPollPeriodMs: 10000
      ipfsStatusTimeoutMs: 200000
      auth:
        type: NONE
    ingress:
      enabled: false
      className: "gce"
      paths:
        - /v3
    replicaCount: 1
    image:
      repository: ghcr.io/digicatapult/dscp-api
      pullPolicy: IfNotPresent
      tag: 'v4.6.7'
    dscpNode:
      enabled: false

    dscpIpfs:
      enabled: false
      dscpNode:
        enabled: false
    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      secretprefix: secretsv2/data/tiertwo-subs/tiertwo
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetiertwo
