apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tiertwo-postgresql
  namespace: tiertwo-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscpapp
        namespace: flux-dscpapp
      chart: examples/dscp-app/charts/postgresql
  releaseName: tiertwo-postgresql
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.4.0
      pullPolicy: IfNotPresent
      debug: false
    global:
      postgresql:
        auth:
          postgresPassword: postgres123
          database: id-service
        service:
          ports:
            postgresql: 5432
    primary:
      initdb:
        scripts:
          create_second_db.sql: |
            CREATE DATABASE "inteli-api";
            GRANT ALL PRIVILEGES ON DATABASE "inteli-api" TO postgres;
        user: postgres
        password: postgres123
