apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-frontend
  namespace: store-ns
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: store-frontend
  interval: 1m
  chart:
   spec:
    chart: examples/supplychain-app/charts/frontend
    sourceRef:
      kind: GitRepository
      name: flux-corda-app
      namespace: flux-corda-app
  values:
    frontend:
      nodePorts:
        port: 8080
        targetPort: 80
      image: ghcr.io/hyperledger/bevel-supplychain-frontend:1.0.0
      pullPolicy: IfNotPresent
      pullSecrets: regcred
      apiURL: https://storeapi.rc.demo.blockchaincloudpoc.com
    deployment:
      annotations: {}
    proxy:
      provider: ambassador
      peer_name: store
      external_url_suffix: rc.demo.blockchaincloudpoc.com
