##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# Create inteli-api values file for the peer nodes
- name: "Create inteli-api values file for all peers"
  include_role:
    name: helm_component
  vars:
    type: "inteli-api"
    component_name: "{{ peer.name }}-inteli-api"
    external_addr: "https://{{ component_name }}.{{ external_suffix }}"
    name: "{{ peer.name }}"
    charts_dir: "examples/dscp-app/charts"
    db_address: "{{ peer.name }}-postgresql"
    dscp_api_addr: "{{ peer.name }}-api"
    id_service_addr: "{{ peer.name }}-id-service"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)

# Push the inteli-api deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ component_gitops }}"
    GIT_RESET_PATH: "examples/dscp-app/configuration"
    msg: "[ci skip] Pushing deployment files for inteli-api"

# Wait for inteli-api Pod to run
- name: "Waiting for inteli-api pod in {{ component_ns }}"
  include_role:
    name: "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ component_ns }}"
    component_name: "{{ peer.name }}-inteli-api"
    kubernetes: "{{ org.k8s }}"
    label_selectors:
      - name = {{ component_name }}
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: (peer.postgresql is defined) and (peer.inteli_api is defined)
