##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

charts:
  restserver: fabric-restserver
  expressapi-corda: expressapp
  expressapi-fabric: expressapp
  webserver: springbootwebserver
  webserver-ent: springbootwebserver
  frontend: frontend
  expressapi-quorum: expressapp-quorum
  expressapi-besu: expressapp-besu
