{{- $adminPassword := .Values.wallet.holder.databaseSecret.adminPassword | required ".Values.wallet.holder.databaseSecret.adminPassword." -}}
{{- $databasePassword := .Values.wallet.holder.databaseSecret.databasePassword | required ".Values.wallet.holder.databaseSecret.databasePassword." -}}
{{- $databaseUser := .Values.wallet.holder.databaseSecret.databaseUser | required ".Values.wallet.holder.databaseSecret.databaseUser." -}}
{{- $databaseAdminUser := .Values.wallet.databaseAdminUser | required ".Values.wallet.databaseAdminUser." -}}
{{- $walletHost := .Values.wallet.host | required ".Values.wallet.host is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aries-agent.holder.secret.database" . }}
  labels:
    {{- include "aries-agent.holder.labelsWithName" . | nindent 4 }}
stringData:
  admin-password: {{ $adminPassword }}
  database-password: {{ $databasePassword }}
  database-user: {{ $databaseUser }}
  storage-creds: "{\"account\":\"{{ $databaseUser }}\",\"password\":\"{{ $databasePassword }}\",\"admin_account\":\"{{ $databaseAdminUser }}\",\"admin_password\":\"{{ $adminPassword }}\"}"
type: Opaque
