{{- $seed := .Values.wallet.holder.credentialSecret.seed | required ".Values.wallet.holder.credentialSecret.seed is required." -}}
{{- $did := .Values.wallet.holder.credentialSecret.did | required ".Values.wallet.holder.credentialSecret.did is required." -}}
{{- $verkey := .Values.wallet.holder.credentialSecret.verkey | required ".Values.wallet.holder.credentialSecret.verkey is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aries-agent.holder.secret.wallet" . }}
  labels:
    {{- include "aries-agent.holder.labelsWithName" . | nindent 4 }}
stringData:
  seed: {{ $seed }}
  did: {{ $did }}
  verkey: {{ $verkey }}
type: Opaque
