apiVersion: v1
kind: Service
metadata:
  name: {{ include "aries-agent.holder.name" . }}
  labels:
    {{- include "aries-agent.holder.labelsWithName" . | nindent 4 }}
spec:
  ports:
    - name: {{ include "aries-agent.holder.name" . }}-admin
      port: {{ int .Values.service.holder.ports.admin }}
      protocol: TCP
      targetPort: {{ int .Values.service.holder.ports.admin }}
    - name: {{ include "aries-agent.holder.name" . }}-http
      port: {{ int .Values.service.holder.ports.http }}
      protocol: TCP
      targetPort: {{ int .Values.service.holder.ports.http }}
  selector:
    {{- include "aries-agent.holder.selectorLabels" . | nindent 4 }}
