{{- $adminApiKey := .Values.wallet.holder.apiKeySecret.admin | required ".Values.wallet.holder.apiKeySecret.admin is required." -}}
{{- $webhookJWT := .Values.wallet.holder.apiKeySecret.webhookJWT | required ".Values.wallet.holder.apiKeySecret.webhookJWT" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aries-agent.holder.secret.api" . }}
  labels:
    {{- include "aries-agent.holder.labelsWithName" . | nindent 4 }}
stringData:
  admin-api-key: "{{ $adminApiKey }}"
  webhook-jwt: "{{ $webhookJWT }}"
type: Opaque
