apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "aries-agent.issuer.name" . }}
  labels:
    {{- include "aries-agent.issuer.labelsWithName" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ include "aries-agent.issuer.name" . }}
  minReplicas: {{ int .Values.service.issuer.replicas.min }}
  maxReplicas: {{ int .Values.service.issuer.replicas.max }}
