{{- $adminApiKey := .Values.wallet.issuer.apiKeySecret.admin | required ".Values.wallet.issuer.apiKeySecret.admin is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aries-agent.issuer.secret.api" . }}
  labels:
    {{- include "aries-agent.issuer.labelsWithName" . | nindent 4 }}
stringData:
  admin-api-key: "{{ $adminApiKey }}"
type: Opaque
