apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aries-agent.deploy-name" . }}-allow-ingress
  labels:
    {{- include "aries-agent.labels" . | nindent 4 }}
    name: {{ include "aries-agent.deploy-name" . }}-allow-ingress
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.ingress.namespace }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "aries-agent.controllerLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.ingress.namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.holder.ports.admin }}
        - protocol: TCP
          port: {{ .Values.service.issuer.ports.admin }}
        - protocol: TCP
          port: {{ .Values.service.verifier.ports.admin }}
  podSelector:
    matchLabels:
      {{- include "aries-agent.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
