apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "aries-agent.verifier.name" . }}
  labels:
    {{- include "aries-agent.verifier.labelsWithName" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ include "aries-agent.verifier.name" . }}
  minReplicas: {{ int .Values.service.verifier.replicas.min }}
  maxReplicas: {{ int .Values.service.verifier.replicas.max }}
