##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chain-watcher-pvc
  namespace: {{ .Values.metadata.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.metadata.storageClass }}
  resources:
    requests:
      storage: 256Mi
