apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tierone-web
  namespace: tierone-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-dscpapp
        namespace: flux-dscpapp
      chart: examples/dscp-app/charts/dscp-frontend
  releaseName: tierone-web
  values:
    fullNameOverride: tierone-web
    config:
      port: 4000
      logLevel: info
      enableLivenessProbe: false
      inteliApiAddr: https://tierone-inteli-api.subs.demo.aws.blockchaincloudpoc.com/v1/
      logo: inteli.svg
      kinaxisUrl: https://na1.kinaxis.net/web/ACCD01_DEM01/
      persona: supplier
    auth:
      enabled: False
    ingress:
      enabled: false
      className: "gce"
      paths:
        - /
    replicaCount: 1
    image:
      repository: ghcr.io/inteli-poc/inteli-frontend  # {"$imagepolicy": "flux-dscpapp:inteli-frontend:name"}
      pullPolicy: Always
      tag: 'v1.3.1-a9b2b40-1673367333' # {"$imagepolicy": "flux-dscpapp:inteli-frontend:tag"}
    vault:
      alpineutils: ghcr.io/hyperledger/alpine-utils:1.0
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      secretprefix: secretsv2/data/tierone-subs
      serviceaccountname: vault-auth
      role: vault-role
      authpath: substratetierone
    proxy:
      provider: ambassador
      name: tierone
      external_url_suffix: subs.demo.aws.blockchaincloudpoc.com
      issuedFor: tierone
