apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-expressapi
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  chart:
   spec:
    chart: examples/supplychain-app/charts/expressapp
    sourceRef:
      kind: GitRepository
      name: flux-demo-fabric-app
      namespace: flux-demo-fabric-app
  releaseName: storefabric-expressapi
  values:
    nodeName: store-expressapi
    metadata:
      namespace: store-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: ghcr.io/hyperledger/bevel-supplychain-fabric:express-app-latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://store-restserver.store-net:20001/api/v1
    proxy:
      provider: haproxy
      name: store
      type: fabric
      external_url_suffix: hf.demo.aws.blockchaincloudpoc.com
      peer_name: peer0
