##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    labels:
      run: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
    type: NodePort
    selector:
      app: {{ .Release.Name }}
    ports:
    - port: {{ .Values.web.port }}
      {{- if .Values.web.nodePort }}
      nodePort: {{ .Values.web.nodePort}}
      {{- end }}      
      targetPort: 20001
      protocol: TCP
      name: web
