apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: carrier-springboot
  namespace: carrier-ns
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-springboot
  interval: 1m
  chart:
    spec:
      chart: examples/supplychain-app/charts/springbootwebserver
      sourceRef:
        kind: GitRepository
        name: flux-corda-app
        namespace: flux-corda-app
  values:
    nodeName: carrier-springboot
    replicas: 1
    metadata:
      namespace: carrier-ns
      type: cordaopensource
    image:
      containerName: ghcr.io/bevel-supplychain-corda:springboot-latest
      initContainerName: ghcr.io/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
    smartContract:
      JAVA_OPTIONS : -Xmx512m
    volume:
      mountPath: /opt/corda
    nodeConf:
      node: carrier
      nodeRpcPort: 10003
      nodeRpcAdminPort: 10005
      controllerName: Controller
      trustStorePath: /opt/corda/certificates/sslkeystore.jks
      trustStoreProvider: jks
      legalName: O=Carrier,OU=Carrier,L=London,C=GB
      devMode: false
      useHTTPS: true
      useSSL: false
      tlsAlias: cordaclienttls
      ssl:
        certificatesDirectory: na-ssl-false
        sslKeystoreFileName: na-ssl-false
        ssltruststore: na-ssl-false
    credentials:
      rpcUser: carrieroperations
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      memory: 512Mi
      name: carrier-azure-storageclass
    web:
      targetPort: 20001
      port: 20001
    service:
      type: NodePort
      annotations: {}
    networkservices:
      networkmap: na
      doorman: na
    vault:
      address: "http://vault.internal.demo.blockchaincloudpoc.com:9001"
      role: vault-role
      authpath: cordacarrier
      serviceaccountname: vault-auth
      rpcusersecretprefix: carrier/data/credentials/rpcusers
      keystoresecretprefix: carrier/data/credentials/keystore
      certsecretprefix: carrier/data/certs
    node:
      readinesscheckinterval: 10
      readinessthreshold: 15
    deployment:
      annotations: {}
    pvc:
      annotations: {}
