apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: warehouse-springboot
  namespace: warehouse-ns
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: warehouse-springboot
  interval: 1m
  chart:
    spec:
      chart: examples/supplychain-app/charts/springbootwebserver
      sourceRef:
        kind: GitRepository
        name: flux-corda-app
        namespace: flux-corda-app
  values:
    image:
      webserver: ghcr.io/hyperledger/bevel-supplychain-corda:springboot-latest
      initContainer: ghcr.io/hyperledger/bevel-alpine:latest
      imagePullSecret: regcred
    smartContract:
      JAVA_OPTIONS : -Xmx512m
    nodeConf:
      node: warehouse
      nodeRpcPort: 10003
      legalName: O=Warehouse,OU=Warehouse,L=42.36/-71.06/Boston,C=US
      devMode: false
      useSSL: false
      readinessCheckInterval: 10
      readinessThreshold: 15
    credentials:
      rpcUser: nodeoperations
      rpcUserPassword: nodeoperationsAdmin
      keystorePassword: newpass
      truststorePassword: newtrustpass
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      memory: 512Mi
      name: storage-warehouse
    web:
      targetPort: 20001
      port: 20001
