##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This playbook deploys the supplychain apis and frontend to an existing DLT network
# The DLT network should already be created using the same configuration file as that
#   used for running this playbook.
---
# This will apply to ansible_provisioners. /etc/ansible/hosts should be configured with this group
- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
  - include_role:
      name:  "{{ playbook_dir }}/../../../platforms/shared/configuration/roles/setup/flux"
    vars:
      kubeconfig_path: "{{ item.k8s.config_file }}"
      kubecontext: "{{ item.k8s.context }}"
      git_username: "{{ item.gitops.username }}"
      git_repo: "{{ item.gitops.git_repo }}"
      git_password: "{{ item.gitops.password }}"
      git_branch: "{{ item.gitops.branch }}"
      git_path: "{{ item.gitops.release_dir }}"
      git_host: "{{ item.gitops.git_repo.split('/')[0] | lower }}" # extract the hostname from the git_repo
      git_protocol: "{{ item.gitops.git_protocol | default('https') }}"
      git_url: "{{ item.gitops.git_url }}"
      git_key: "{{ item.gitops.private_key | default() }}"
      flux_version: "0.35.0"
    with_items: "{{ network.organizations }}"

  - name: Copy test env files to build directory
    copy:
      src: "{{ item }}"
      dest: "{{ playbook_dir }}/../../../build/"
    with_fileglob:
      - "{{ playbook_dir }}/../tests/SupplychainDemo_*"
  ############################################################################################
  # Create restserver value file for the peer nodes
  - include_role:
      name: "create/fabric/restserver"
    vars:
      component_name: "restserver"
      component_ns: "{{ organization_data.name | lower }}-net"
      component_type: "{{ organization_data.type | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}/{{ organization_data.name | lower }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'fabric'

  ############################################################################################
  # Create express API value file for the peer nodes
  - include_role:
      name: "create/fabric/expressapi"
    vars:
      component_name: "expressapi"
      component_ns: "{{ organization_data.name | lower }}-net"
      component_type: "{{ organization_data.type | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}/{{ organization_data.name | lower }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'fabric'
  
  ############################################################################################
  # Create webserver value file for the corda nodes
  - include_role:
      name: "create/corda/webserver"
    vars:
      component_name: "webserver"
      component_ns: "{{ organization_data.name | lower }}-ns"
      component_type: "{{ organization_data.type | default(' ', true) | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'corda' and component_type == 'node'

  # Create webserver value file for the corda enterprise nodes
  - include_role:
      name: "create/corda/webserver"
    vars:
      component_name: "webserver"
      component_ns: "{{ organization_data.name | lower }}-ent"
      component_type: "{{ organization_data.type | default(' ', true) | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'corda-enterprise' and component_type == 'node'
  
  ############################################################################################
  # Create expressapi value file for the corda opensource nodes
  - include_role:
      name: "create/corda/expressapi"
    vars:
      component_name: "expressapi"
      component_ns: "{{ organization_data.name | lower }}-ns"
      component_type: "{{ organization_data.type | default(' ', true) | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'corda' and component_type == 'node'
  
  # Create expressapi value file for the corda enterprise nodes
  - include_role:
      name: "create/corda/expressapi"
    vars:
      component_name: "expressapi"
      component_ns: "{{ organization_data.name | lower }}-ent"
      component_type: "{{ organization_data.type | default(' ', true) | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'corda-enterprise' and component_type == 'node'

  ############################################################################################
  # Create frontend value file for the corda nodes
  - include_role:
      name: "create/corda/frontend"
    vars:
      component_name: "frontend"
      component_ns: "{{ organization_data.name | lower }}-ns"
      component_type: "{{ organization_data.type | default(' ', true) | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      kubernetes: "{{ organization_data.k8s }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data 
    when: 
    - network['type'] == 'corda'
    - network['frontend'] == 'enabled' 
    - component_type == 'node'

  ############################################################################################
  # Create frontend value file for the corda nodes
  - include_role:
      name: "create/fabric/frontend"
    vars:
      component_name: "frontend"
      component_ns: "{{ organization_data.name | lower }}-net"
      component_type: "{{ organization_data.type | default(' ', true) | lower  }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      kubernetes: "{{ organization_data.k8s }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'fabric' and network['frontend'] == 'enabled' and component_type == 'peer'

  # Call the initialize function to set the blockchain as invoke does not work for external chaincodes
  - name: Call initialize API
    uri:
      url: "https://{{ component_name }}.{{ component_url }}/api/v1/initialize"
      method: GET
      status_code: 200  # expected status code
    vars:
      component_name: "{{ organization_data.name | lower }}api"
      component_url: "{{ organization_data.external_url_suffix }}"
      component_type: "{{ organization_data.type | default(' ', true) | lower  }}"
      external_chaincode: "{{ organization_data.services.peers[0].chaincodes[0].external_chaincode | default(false) }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: 
    - network['type'] == 'fabric'
    - component_type == 'peer'
    - external_chaincode
  
  ############################################################################################
  # Deploy the Smart contract on Quorum node
  - name: "Deploying smartcontract on quorum node"
    include_role:
      name: "deploy/quorum/smartContract"
    vars:
      component_ns: "{{ organization_data.name | lower }}-quo"
      component_vault: "{{ organization_data.vault }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'quorum'
  
  # Place the smart contract in the vault of the organization
  - name: "Adding SmartContract address to the other organizations"
    include_role:
      name: "setup/smartContractAddress"
    vars:
      component_ns: "{{ organization_data.name | lower }}-quo"
      component_vault: "{{ organization_data.vault }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'quorum' and check != "Error"

  ############################################################################################
  # Create expressapi value file for the quorum nodes
  - include_role:
      name: "create/quorum/expressapi"
    vars:
      component_name: "expressapi"
      component_ns: "{{ organization_data.name | lower }}-quo"
      component_type: "{{ organization_data.type | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}/{{ organization_data.name | lower }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'quorum'
  ############################################################################################
  # Create frontend value file for the quorum nodes
  - include_role:
      name: "create/quorum/frontend"
    vars:
      component_name: "frontend"
      component_ns: "{{ organization_data.name | lower }}-quo"
      component_type: "{{ organization_data.type | default(' ', true) | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      kubernetes: "{{ organization_data.k8s }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}/{{ organization_data.name | lower }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data 
    when: network['type'] == 'quorum' and network['frontend'] == 'enabled'

  ############################################################################################
  # Deploy the Smart contract on besu node
  - name: "Deploying smartcontract on besu node"
    include_role:
      name: "deploy/besu/smartContract"
    vars:
      component_ns: "{{ organization_data.name | lower }}-bes"
      component_vault: "{{ organization_data.vault }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'besu'

# Place the smart contract in the vault of the organization
  - name: "Adding SmartContract address to the other organizations"
    include_role:
      name: "setup/smartContractAddress"
    vars:
      component_ns: "{{ organization_data.name | lower }}-bes"
      component_vault: "{{ organization_data.vault }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: network['type'] == 'besu' and check != "Error"

# Create expressapi value file for the besu nodes
  - name: "Creating express app values files for Besu nodes"
    include_role:
      name: "create/besu/express_api"
    vars:
      component_ns: "{{ organization_data.name | lower }}-bes"
      component_type: "{{ organization_data.type | lower }}"
      component_gitops: "{{ organization_data.gitops }}"
      component_vault: "{{ organization_data.vault }}"
      values_dir: "{{ playbook_dir }}/../../../{{ organization_data.gitops.release_dir }}/{{ organization_data.name | lower }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: organization_data
    when: 
      - network['type'] == 'besu' 
      - component_type != "validator"
  vars: #These variables can be overriden from the command line
    install_os: "linux"           # Default to linux OS
    install_arch:  "amd64"        # Default to amd64 architecture
    bin_install_dir:  "~/bin"     # Default to /bin install directory for binaries
